create table if not exists profiles (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, email text not null, full_name text not null default '', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists study_sessions (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, title text not null, description text not null default '', start_time timestamptz not null, end_time timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists ai_usage_logs (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, feature_used text not null, prompt_tokens integer not null default 0, completion_tokens integer not null default 0, total_tokens integer not null default 0, created_at timestamptz not null default now());
create table if not exists calendar_connections (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, provider text not null, access_token_encrypted text not null default '', refresh_token_encrypted text not null default '', scope text not null default '', expires_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
alter table profiles enable row level security; alter table study_sessions enable row level security; alter table ai_usage_logs enable row level security; alter table calendar_connections enable row level security;
create policy profiles_select_own on profiles for select using (auth.uid() = user_id); create policy profiles_insert_own on profiles for insert with check (auth.uid() = user_id); create policy profiles_update_own on profiles for update using (auth.uid() = user_id) with check (auth.uid() = user_id); create policy profiles_delete_own on profiles for delete using (auth.uid() = user_id);
create policy study_sessions_select_own on study_sessions for select using (auth.uid() = user_id); create policy study_sessions_insert_own on study_sessions for insert with check (auth.uid() = user_id); create policy study_sessions_update_own on study_sessions for update using (auth.uid() = user_id) with check (auth.uid() = user_id); create policy study_sessions_delete_own on study_sessions for delete using (auth.uid() = user_id);
create policy ai_usage_logs_select_own on ai_usage_logs for select using (auth.uid() = user_id); create policy ai_usage_logs_insert_own on ai_usage_logs for insert with check (auth.uid() = user_id);
create policy calendar_connections_select_own on calendar_connections for select using (auth.uid() = user_id); create policy calendar_connections_insert_own on calendar_connections for insert with check (auth.uid() = user_id); create policy calendar_connections_update_own on calendar_connections for update using (auth.uid() = user_id) with check (auth.uid() = user_id); create policy calendar_connections_delete_own on calendar_connections for delete using (auth.uid() = user_id);
